#!/bin/bash
DIR=$( pwd )
CODE_DIR="$DIR/Rat-Grammer/Antlr/Rat.g4"
GEN_CODE_DIR="$DIR/Rat-Grammer/Autogenerated"
JAR_PATH="$DIR/Deps/antlr4-4.6-complete.jar"
ANTLR_DIR="$DIR/Rat-Grammer/Antlr"

java "-jar" "$JAR_PATH" "-Dlanguage=CSharp" "-o" "$GEN_CODE_DIR" "-listener" "-visitor" "-lib" "$ANTLR_DIR" "$CODE_DIR" 
