//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/lord_faceless/RiderProjects/Rat/Rat-Grammer/Antlr/rat.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRatListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class RatBaseListener : IRatListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] RatParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] RatParser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.extdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtdef([NotNull] RatParser.ExtdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.extdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtdef([NotNull] RatParser.ExtdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.ifblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfblock([NotNull] RatParser.IfblockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.ifblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfblock([NotNull] RatParser.IfblockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.typedef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedef([NotNull] RatParser.TypedefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.typedef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedef([NotNull] RatParser.TypedefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncdef([NotNull] RatParser.FuncdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncdef([NotNull] RatParser.FuncdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.expressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressions([NotNull] RatParser.ExpressionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.expressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressions([NotNull] RatParser.ExpressionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] RatParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] RatParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.leftUnaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeftUnaryOperator([NotNull] RatParser.LeftUnaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.leftUnaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeftUnaryOperator([NotNull] RatParser.LeftUnaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.rightUnaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRightUnaryOperator([NotNull] RatParser.RightUnaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.rightUnaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRightUnaryOperator([NotNull] RatParser.RightUnaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.zeroLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterZeroLevelOperator([NotNull] RatParser.ZeroLevelOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.zeroLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitZeroLevelOperator([NotNull] RatParser.ZeroLevelOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.firstLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirstLevelOperator([NotNull] RatParser.FirstLevelOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.firstLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirstLevelOperator([NotNull] RatParser.FirstLevelOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.secondLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSecondLevelOperator([NotNull] RatParser.SecondLevelOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.secondLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSecondLevelOperator([NotNull] RatParser.SecondLevelOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.thirdLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThirdLevelOperator([NotNull] RatParser.ThirdLevelOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.thirdLevelOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThirdLevelOperator([NotNull] RatParser.ThirdLevelOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.forthLevelOpeator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForthLevelOpeator([NotNull] RatParser.ForthLevelOpeatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.forthLevelOpeator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForthLevelOpeator([NotNull] RatParser.ForthLevelOpeatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] RatParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] RatParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.functype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctype([NotNull] RatParser.FunctypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.functype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctype([NotNull] RatParser.FunctypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.funcarg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncarg([NotNull] RatParser.FuncargContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.funcarg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncarg([NotNull] RatParser.FuncargContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.tupledef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupledef([NotNull] RatParser.TupledefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.tupledef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupledef([NotNull] RatParser.TupledefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] RatParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] RatParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.tupletype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupletype([NotNull] RatParser.TupletypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.tupletype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupletype([NotNull] RatParser.TupletypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg([NotNull] RatParser.ArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg([NotNull] RatParser.ArgContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
