//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/lord_faceless/RiderProjects/Rat/Rat-Grammer/Antlr/rat.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RatParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IRatListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode([NotNull] RatParser.CodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode([NotNull] RatParser.CodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.extdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtdef([NotNull] RatParser.ExtdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.extdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtdef([NotNull] RatParser.ExtdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.ifblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfblock([NotNull] RatParser.IfblockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.ifblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfblock([NotNull] RatParser.IfblockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedef([NotNull] RatParser.TypedefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedef([NotNull] RatParser.TypedefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncdef([NotNull] RatParser.FuncdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncdef([NotNull] RatParser.FuncdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressions([NotNull] RatParser.ExpressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressions([NotNull] RatParser.ExpressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] RatParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] RatParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.leftUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftUnaryOperator([NotNull] RatParser.LeftUnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.leftUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftUnaryOperator([NotNull] RatParser.LeftUnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.rightUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRightUnaryOperator([NotNull] RatParser.RightUnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.rightUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRightUnaryOperator([NotNull] RatParser.RightUnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.zeroLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZeroLevelOperator([NotNull] RatParser.ZeroLevelOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.zeroLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZeroLevelOperator([NotNull] RatParser.ZeroLevelOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.firstLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFirstLevelOperator([NotNull] RatParser.FirstLevelOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.firstLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFirstLevelOperator([NotNull] RatParser.FirstLevelOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.secondLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecondLevelOperator([NotNull] RatParser.SecondLevelOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.secondLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecondLevelOperator([NotNull] RatParser.SecondLevelOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.thirdLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThirdLevelOperator([NotNull] RatParser.ThirdLevelOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.thirdLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThirdLevelOperator([NotNull] RatParser.ThirdLevelOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.forthLevelOpeator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForthLevelOpeator([NotNull] RatParser.ForthLevelOpeatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.forthLevelOpeator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForthLevelOpeator([NotNull] RatParser.ForthLevelOpeatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] RatParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] RatParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.functype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctype([NotNull] RatParser.FunctypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.functype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctype([NotNull] RatParser.FunctypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.funcarg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncarg([NotNull] RatParser.FuncargContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.funcarg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncarg([NotNull] RatParser.FuncargContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.tupledef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupledef([NotNull] RatParser.TupledefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.tupledef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupledef([NotNull] RatParser.TupledefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] RatParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] RatParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.tupletype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupletype([NotNull] RatParser.TupletypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.tupletype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupletype([NotNull] RatParser.TupletypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RatParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] RatParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RatParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] RatParser.ArgContext context);
}
