//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/lord_faceless/RiderProjects/Rat/Rat-Grammer/Antlr/Rat.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RatParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IRatVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode([NotNull] RatParser.CodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.statementblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementblock([NotNull] RatParser.StatementblockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] RatParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressions([NotNull] RatParser.ExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] RatParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.leftoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftoperator([NotNull] RatParser.LeftoperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.zerooperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZerooperator([NotNull] RatParser.ZerooperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.firstoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFirstoperator([NotNull] RatParser.FirstoperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.secondoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondoperator([NotNull] RatParser.SecondoperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.thirdoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThirdoperator([NotNull] RatParser.ThirdoperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncdef([NotNull] RatParser.FuncdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.funcargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncargs([NotNull] RatParser.FuncargsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.funcarg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncarg([NotNull] RatParser.FuncargContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.funccall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunccall([NotNull] RatParser.FunccallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.exprargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprargs([NotNull] RatParser.ExprargsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.ifexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfexpr([NotNull] RatParser.IfexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstmt([NotNull] RatParser.IfstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] RatParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] RatParser.RangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] RatParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] RatParser.NumberContext context);
}
