//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/lord_faceless/RiderProjects/Rat/Rat-Grammer/Antlr/rat.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RatParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IRatVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode([NotNull] RatParser.CodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.extdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtdef([NotNull] RatParser.ExtdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.ifblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfblock([NotNull] RatParser.IfblockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedef([NotNull] RatParser.TypedefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncdef([NotNull] RatParser.FuncdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressions([NotNull] RatParser.ExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] RatParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.leftUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftUnaryOperator([NotNull] RatParser.LeftUnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.rightUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRightUnaryOperator([NotNull] RatParser.RightUnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.zeroLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZeroLevelOperator([NotNull] RatParser.ZeroLevelOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.firstLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFirstLevelOperator([NotNull] RatParser.FirstLevelOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.secondLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondLevelOperator([NotNull] RatParser.SecondLevelOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.thirdLevelOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThirdLevelOperator([NotNull] RatParser.ThirdLevelOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.forthLevelOpeator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForthLevelOpeator([NotNull] RatParser.ForthLevelOpeatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] RatParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.functype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctype([NotNull] RatParser.FunctypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.funcarg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncarg([NotNull] RatParser.FuncargContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.tupledef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupledef([NotNull] RatParser.TupledefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] RatParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.tupletype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupletype([NotNull] RatParser.TupletypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RatParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] RatParser.ArgContext context);
}
